version: '3.8'

services:
  web:
    build: ./Project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Project/:/usr/src/Project/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine3.17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5455:5432"
    environment:
      - POSTGRES_USER=my_proj
      - POSTGRES_PASSWORD=my_proj
      - POSTGRES_DB=my_proj_dev
  redis:
    image: redis:6.2.5-alpine3.14
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    depends_on:
      - web
  celery:
    build: ./Project
    command: celery -A main worker -l info
    volumes:
      - ./Project/:/usr/src/Project/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis


volumes:
  postgres_data:
  redis_data:
  Project: